folder = []
label = "gofl"
name = "go-flat"

[[file]]
  destination = "README.md"
  template = "README.md"

[[file]]
  destination = "main.go"
  template = "main.go"

[[script]]
  name = "init_git.sh"
  type = "post"
  execNumber = 1
  runAsSudo = false
  args = []
